import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: typeof translations.ru;
}

export const translations = {
  ru: {
    nav: {
      about: 'О компании',
      history: 'История',
      fleet: 'Автопарк',
      geography: 'Направления',
      advantages: 'Преимущества',
      services: 'Услуги',
      faq: 'Вопросы',
      requisites: 'Реквизиты',
      contacts: 'Контакты',
      contactBtn: 'Связаться',
      directPhone: 'Прямой звонок',
    },
    hero: {
      badge: 'Официальная визитка международной транспортной компании',
      title1: 'Международные грузоперевозки',
      title2: 'Европа • Китай • СНГ',
      title3: 'собственным и привлеченным парком',
      description: 'Прямая логистика без посредников: регулярные рейсы по странам СНГ (Россия, Беларусь, Казахстан), прямые и мультимодальные поставки из Китая и стран Европы. Современные еврофуры, рефрижераторы, негабаритные перевозки и полное таможенное сопровождение.',
      highlight1Title: 'Собственные еврофуры и рефы',
      highlight1Sub: 'С постоянным контролем температуры',
      highlight2Title: 'Прямая связь с руководством',
      highlight2Sub: 'Без диспетчеров-посредников',
      btnHistory: 'История компании',
      btnFleet: 'Наш автопарк',
      btnContact: 'Связаться с нами',
      stats: {
        stat1Num: '14.5k+',
        stat1Label: 'Рейсов по СНГ и миру',
        stat2Num: '99.8%',
        stat2Label: 'Своевременность доставки',
        stat3Num: '100%',
        stat3Label: 'CMR / ТТН Страхование',
        stat4Num: '2010 г.',
        stat4Label: 'Старт деятельности',
      },
      advantages: {
        item1Title: 'Надёжность',
        item1Sub: 'Мы ценим доверие',
        item2Title: 'Своевременность',
        item2Sub: 'Чёткая доставка в срок',
        item3Title: 'Покрытие',
        item3Sub: 'По всей Армении и за её пределами',
        item4Title: 'Партнёрство',
        item4Sub: 'Долгосрочные отношения',
      },
      servicesHeader: 'Наши направления',
      servicesTitle: 'Перевозки высшего класса',
      servicesSub: 'Предоставляем безупречные условия для любых логистических задач вашего бизнеса',
      directions: [
        {
          id: 'road',
          name: 'Автомобильные перевозки (Тенты и Рефрижераторы)',
          description: 'Международная доставка генеральных, сборных и температурных грузов по СНГ собственным автопарком. Еврофуры и рефрижераторы от -20°C до +12°C.',
          speed: 'Индивидуально',
          footnote: '«Собственный автопарк еврофур и рефов»',
        },
        {
          id: 'oversized',
          name: 'Негабаритные и тяжеловесные грузы (Экспедирование)',
          description: 'Организация и экспедирование перевозок КТГ под ключ по СНГ. Транспортировка спецтехники, промышленного оборудования и длинномерных конструкций. Полное сопровождение: подбор специализированных тралов, разработка маршрутов, оформление разрешений и пропусков.',
          speed: 'Индивидуально',
          footnote: '«Спецтранспорт и разрешения под ключ»',
        },
        {
          id: 'air',
          name: 'Авиадоставка',
          description: 'Срочная доставка экспресс-грузов, коммерческих партий и ценных отправлений через международные аэропорты СНГ.',
          speed: 'Индивидуально',
          footnote: '«Экспресс-доставка ценных грузов»',
        },
        {
          id: 'rail',
          name: 'Железнодорожные перевозки',
          description: 'Экономичная контейнерная доставка (20фт / 40фт) больших объемов грузов, оборудования и сырья на дальние расстояния.',
          speed: 'Индивидуально',
          footnote: '«Контейнерные ж/д перевозки»',
        },
        {
          id: 'sea',
          name: 'Морские перевозки',
          description: 'Мультимодальные контейнерные перевозки через ключевые морские порты с дальнейшим вывозом автотранспортом до склада получателя.',
          speed: 'Индивидуально',
          footnote: '«Мультимодальные маршруты»',
        },
      ],
      faqHeader: 'Отвечаем на ваши вопросы',
      faqTitle: 'Часто задаваемые вопросы',
      faqSub: 'Полезная информация о международной B2B логистике, оформлении и гарантиях',
      faqItems: [
        {
          question: 'Какие документы необходимы для международной перевозки грузов по СНГ?',
          answer: 'Для юридических лиц требуются: международная товарно-транспортная накладная (CMR), инвойс (счет-фактура) с подробной спецификацией груза, упаковочный лист, техническая документация (паспорт изделия или сертификат соответствия) и внешнеторговый контракт. Наши специалисты оказывают полную поддержку в подготовке и проверке всего пакета документов для быстрого прохождения таможенных процедур.'
        },
        {
          question: 'Как определяются сроки доставки грузов?',
          answer: 'Сроки доставки рассчитываются индивидуально для каждой перевозки с учетом специфики груза, типа подвижного состава, точного маршрута, погодных условий и текущей обстановки на пограничных контрольно-пропускных пунктах (включая КПП «Верхний Ларс»). Точный график и контрольные точки согласовываются и фиксируются в договоре-заявке.'
        },
        {
          question: 'Обеспечиваете ли вы температурный режим и как гарантируется сохранность груза?',
          answer: 'Да, в нашем автопарке имеются современные рефрижераторы с сертифицированными термописцами, поддерживающими температурный диапазон от -20°C до +12°C. Сохранность грузов гарантируется обязательным пломбированием кузова, GPS-мониторингом 24/7 в реальном времени и страхованием ответственности перевозчика (CMR-страхование) для каждого рейса.'
        },
        {
          question: 'Работаете ли вы с НДС и какие условия оплаты предусмотрены для юридических лиц?',
          answer: 'Да, мы работаем по официальным B2B-договорам как с НДС, так и без НДС. Оплата производится безналичным расчетом в рублях (RUB), драмах (AMD) или другой согласованной валюте. Для постоянных корпоративных партнеров предусмотрены гибкие условия, включая частичную постоплату и отсрочку платежа.'
        }
      ],
      contactsHeader: 'Прямая связь без посредников',
      contactsTitle: 'Контакты и Руководство',
      contactsSub: 'Персонализированный подход для крупных B2B-клиентов и долгосрочных контрагентов',
      salesRole: 'B2B ПРОДАЖИ',
      salesName: 'Саргис Варданян',
      salesDesc: 'Ведущий менеджер по работе с ключевыми B2B клиентами',
      salesPhoneLabel: 'Прямой телефон связи',
      messengersLabel: 'Быстрый переход в мессенджеры',
      ceoRole: 'РУКОВОДСТВО',
      ceoName: 'Аветик Зограбян',
      ceoDesc: 'Генеральный директор ООО «ЛЕВ ЭНД АВ»',
      ceoPhoneLabel: 'Телефон директора',
      ceoEmailLabel: 'Прямой E-mail',
      adminRole: 'ОБЩИЕ ВОПРОСЫ',
      adminName: 'Администрация и Диспетчерская',
      adminDesc: 'Связь / Диспетчерская служба и Резервный номер компании',
      adminPhonesLabel: 'Телефоны службы поддержки',
      adminEmailLabel: 'Корпоративный E-mail',
      workingHours: 'График: Пн-Сб 09:00 - 19:00',
      timezone: 'Ереван (GMT+4)',
      downloadCardBtn: 'Сохранить контакт (.vcf)',
    },
    history: {
      header: 'Наш путь и принципы',
      title: 'История компании',
      titleAccent: 'LEV&AV',
      subtitle: 'От первых грузовых рейсов до проверенного международного перевозчика со стабильным автопарком и безупречной деловой репутацией.',
      badge: 'О КОМПАНИИ ООО «ЛЕВ ЭНД АВ»',
      mainTitle: 'Надежный логистический мост между Арменией и странами СНГ',
      desc1: 'Компания ООО «ЛЕВ ЭНД АВ» (LEV&AV LLC) ведет свою деятельность в сфере грузоперевозок с 2010 года. С первых дней нашей главной целью стало предоставление прямого, честного и высококачественного сервиса без скрытых наценок и посредников.',
      desc2: 'За годы успешной работы мы сформировали крепкую материально-техническую базу: собственный автопарк тентованных еврофур и современных рефрижераторов, позволяющий транспортировать генеральные, сборные, температурные и негабаритные грузы на любые расстояния.',
      statFounded: 'Старт деятельности',
      statCoverage: 'Покрытие сети',
      statTransits: 'Безопасных рейсов',
      timelineTitle: 'Ключевые этапы развития',
      events: [
        {
          year: '2010',
          title: 'Старт деятельности компании в Ереване',
          description: 'Начало логистической деятельности в сфере автомобильных грузоперевозок, формирование команды опытных водителей и запуск первых регулярных маршрутов.',
          tag: 'Старт с 2010 года',
        },
        {
          year: '2015',
          title: 'Формирование собственного парка еврофур',
          description: 'Приобретение современных магистральных тягачей и тентованных полуприцепов для надежной перевозки генеральных и сборных грузов по странам СНГ.',
          tag: 'Собственный автопарк',
        },
        {
          year: '2019',
          title: 'Запуск рефрижераторного направления',
          description: 'Приобретение современных полуприцепов-рефрижераторов с сертифицированными термописцами (диапазон от -20°C до +12°C), что позволило гарантировать сохранность скоропортящихся грузов в любое время года.',
          tag: 'Собственные рефрижераторы',
        },
        {
          year: '2024–2026',
          title: 'Выход на маршруты Беларуси и Казахстана, цифровой контроль',
          description: 'Расширение географии перевозок по всему СНГ. Оснащение 100% автопарка спутниковым GPS-мониторингом, страхование каждого рейса по CMR и обеспечение прямой связи клиентов с первыми лицами компании.',
          tag: 'Современный уровень',
        },
      ],
      valuesTitle: 'Наши фундаментальные принципы',
      values: [
        {
          title: 'Прямой контакт с руководством',
          description: 'Мы исключаем цепочки посредников. Все ключевые вопросы согласовываются напрямую с генеральным директором и ведущим менеджером.',
        },
        {
          title: 'Собственный парк и надежные водители',
          description: 'Автомобили находятся в безупречном техническом состоянии, а за рулем работают опытные дальнобойщики с многолетним стажем международных рейсов.',
        },
        {
          title: 'Строгое соблюдение обязательств',
          description: 'Фиксированные тарифы без скрытых доплат, своевременная подача транспорта и постоянное информирование заказчика о местонахождении груза.',
        },
        {
          title: 'Безопасность и страхование',
          description: 'Обязательное пломбирование, полное документальное сопровождение (CMR, инвойсы, УПД) и страхование ответственности перевозчика.',
        },
      ],
    },
    fleet: {
      header: 'Техническая база',
      title: 'Собственный автопарк',
      titleAccent: 'LEV&AV',
      subtitle: 'Современные магистральные тягачи европейских брендов и надежные полуприцепы, готовые к рейсам любой сложности в любых погодных условиях.',
      categories: [
        {
          title: 'Рефрижераторные полуприцепы',
          subtitle: 'Температурные перевозки от -20°C до +12°C',
          capacity: 'до 22 тонн / 86–88 м³ / 33 европаллеты',
          specs: [
            'Сертифицированные автономные установки Thermo King / Carrier',
            'Электронные термописцы и непрерывная распечатка термочека',
            'Идеально для свежих фруктов, овощей, напитков, сыров и мяса',
            'Санитарная обработка и герметичные уплотнители дверей',
          ],
          highlight: 'Постоянный контроль температуры',
        },
        {
          title: 'Тентованные еврофуры (Шторы / Борта)',
          subtitle: 'Генеральные и сборные грузы по СНГ',
          capacity: 'до 20–22 тонн / 90–92 м³ / 33 европаллеты',
          specs: [
            'Все виды погрузки: задняя, боковая с обеих сторон и верхняя растентовка',
            'Стяжные ремни, противооткатные упоры, коники и крепежные цепи',
            'Прочные армированные тенты с защитой от осадков и пыли',
            'Обязательное номерное пломбирование кузова перед отправкой',
          ],
          highlight: 'Универсальная вместимость',
        },
        {
          title: 'Тралы и негабаритный транспорт',
          subtitle: 'Перевозка КТГ и промышленного оборудования',
          capacity: 'Индивидуальная грузоподъемность до 45+ тонн',
          specs: [
            'Низкорамные платформы и раздвижные тралы с аппарелями',
            'Транспортировка строительной, дорожной и аграрной спецтехники',
            'Оформление специальных разрешений и пропусков по маршруту',
            'Организация автомобилей сопровождения и экспедирования',
          ],
          highlight: 'Тяжеловесные решения под ключ',
        },
      ],
      capLabel: 'Грузоподъемность / Объем:',
      standard: 'Стандарт Евро-5 / Евро-6',
      readiness: '100% готовность к рейсу',
      maintenanceTitle: 'Регулярное ТО',
      maintenanceDesc: 'Каждый тягач и прицеп проходит полный технический осмотр перед каждым выездом.',
      gpsTitle: 'GPS 24/7 Телематика',
      gpsDesc: 'Непрерывный спутниковый трекинг скорости, координат и температуры внутри кузова.',
      crewTitle: 'Опытный экипаж',
      crewDesc: 'Водители-международники со стажем от 10 лет и знанием всех нюансов горных перевалов.',
    },
    geography: {
      header: 'Международные логистические коридоры',
      title: 'География перевозок',
      titleAccent: 'Европа • Китай • СНГ',
      subtitle: 'Налаженные прямые автомобильные и мультимодальные маршруты связывают Республику Армения и страны СНГ с ключевыми промышленными и торговыми центрами Европы, Китая и Евразийского экономического союза.',
      filterAll: 'Все направления',
      filterCIS: 'СНГ и ЕАЭС',
      filterEurope: 'Европа и ЕС',
      filterChina: 'Китай и Азия',
      routeNum: 'Коридор #',
      fromLabel: 'Откуда:',
      toLabel: 'Куда:',
      frequencyLabel: 'Регулярность:',
      truckTypeLabel: 'Тип транспорта:',
      customsLabel: 'Оформление и хабы:',
      routes: [
        // CIS Corridors
        {
          id: 'cis-moscow',
          category: 'cis',
          regionBadge: 'СНГ • РФ',
          from: 'Ереван (Армения)',
          to: 'Москва и Центральный ФО (Россия)',
          time: 'Индивидуально',
          frequency: 'Ежедневные отправки',
          type: 'Тенты 20т (90–92 м³), Рефрижераторы (-20°C...+12°C)',
          checkpoint: 'КПП Верхний Ларс (Грузия — РФ) / Прямой коридор',
          customsDocs: 'CMR, Инвойс, ТТН, Сертификаты СТ-1, ЕАЭС очистка',
        },
        {
          id: 'cis-spb',
          category: 'cis',
          regionBadge: 'СНГ • РФ',
          from: 'Ереван (Армения)',
          to: 'Санкт-Петербург и СЗФО (Россия)',
          time: 'Индивидуально',
          frequency: '3–4 рейса в неделю',
          type: 'Еврофуры, рефрижераторы, сборные партии (LTL)',
          checkpoint: 'Транзитная автомагистраль М-10 / М-11',
          customsDocs: 'Полное документальное сопровождение ЕАЭС',
        },
        {
          id: 'cis-south',
          category: 'cis',
          regionBadge: 'СНГ • ЮФО',
          from: 'Ереван (Армения)',
          to: 'Краснодар, Ростов-на-Дону, Ставрополь (ЮФО)',
          time: 'Индивидуально',
          frequency: 'Ежедневно (экспресс-подача)',
          type: 'Срочная доставка скоропорта, напитков и агропродукции',
          checkpoint: 'Прямой южный автодорожный коридор',
          customsDocs: 'Фитосанитарный контроль, термочеки, CMR',
        },
        {
          id: 'cis-minsk',
          category: 'cis',
          regionBadge: 'СНГ • Беларусь',
          from: 'Ереван (Армения)',
          to: 'Минск, Брест, Гродно (Беларусь)',
          time: 'Индивидуально',
          frequency: 'Регулярные рейсы по графику',
          type: 'Тентованные автопоезда 20–22т, сборные грузы',
          checkpoint: 'Беспрепятственный транзит через ЕАЭС',
          customsDocs: 'Единые таможенные правила Евразийского союза',
        },
        {
          id: 'cis-kz',
          category: 'cis',
          regionBadge: 'СНГ • Казахстан',
          from: 'Ереван (Армения)',
          to: 'Алматы, Астана, Шымкент (Казахстан)',
          time: 'Индивидуально',
          frequency: '2–3 раза в неделю и под заказ',
          type: 'Еврофуры 90–92 м³, рефрижераторы, негабаритные тралы',
          checkpoint: 'Транскаспийский коридор / Северный маршрут',
          customsDocs: 'Электронные транзитные декларации ЕАЭС',
        },
        {
          id: 'cis-ural',
          category: 'cis',
          regionBadge: 'СНГ • Урал и Сибирь',
          from: 'Ереван (Армения)',
          to: 'Екатеринбург, Челябинск, Казань, Новосибирск',
          time: 'Индивидуально',
          frequency: 'Регулярно (круглогодично)',
          type: 'Генеральные и сборные грузы, промышленное сырье',
          checkpoint: 'Транссибирская магистраль / М-5, М-7',
          customsDocs: 'Спутниковый GPS-трекинг на всем маршруте',
        },
        {
          id: 'cis-return',
          category: 'cis',
          regionBadge: 'СНГ • Обратная загрузка',
          from: 'Города РФ, Беларуси и Казахстана',
          to: 'Ереван и регионы Республики Армения',
          time: 'Индивидуально',
          frequency: 'Постоянный поток возвратных рейсов',
          type: 'Оборудование, металлопрокат, стройматериалы, FMCG',
          checkpoint: 'Специальные льготные тарифы на обратную доставку',
          customsDocs: 'Прямые B2B контракты, закрытие экспорта/импорта',
        },

        // Europe Corridors
        {
          id: 'eu-central',
          category: 'europe',
          regionBadge: 'Европа • Германия / Польша',
          from: 'Германия, Польша, Чехия, Нидерланды',
          to: 'Армения / Россия / Казахстан',
          time: 'Индивидуально',
          frequency: 'Еженедельные консолидированные рейсы',
          type: 'Тентованные еврофуры 92 м³, рефрижераторы, термобоксы',
          checkpoint: 'Таможенные терминалы ЕС / Carnet TIR / T1 / EX-1',
          customsDocs: 'Экспортная декларация EX-1, транзитная T1, CMR',
        },
        {
          id: 'eu-south',
          category: 'europe',
          regionBadge: 'Европа • Италия / Франция',
          from: 'Италия, Франция, Испания, Австрия',
          to: 'Армения и страны ЕАЭС',
          time: 'Индивидуально',
          frequency: 'Регулярные прямые и сборные рейсы',
          type: 'Генеральные партии, оборудование, виноделие, одежда',
          checkpoint: 'Европейские консолидационные хабы (Верона, Милан)',
          customsDocs: 'Таможенная очистка, страхование грузов по CMR',
        },
        {
          id: 'eu-baltic',
          category: 'europe',
          regionBadge: 'Европа • Страны Балтии',
          from: 'Литва (Вильнюс, Клайпеда), Латвия (Рига), Эстония',
          to: 'Ереван и регионы СНГ',
          time: 'Индивидуально',
          frequency: '2 раза в неделю',
          type: 'Сборные грузы от 1 паллеты, контейнерные автопоезда',
          checkpoint: 'Консолидационные склады класса А в Прибалтике',
          customsDocs: 'Переупаковка, маркировка DataMatrix, транзитные T1',
        },
        {
          id: 'eu-tr',
          category: 'europe',
          regionBadge: 'Турция • Ближний Восток',
          from: 'Стамбул, Бурса, Измир, Мерсин (Турция)',
          to: 'Армения / Грузия / РФ',
          time: 'Индивидуально',
          frequency: 'Регулярные автопоезда',
          type: 'Текстиль, промышленное сырье, автозапчасти, химия',
          checkpoint: 'КПП Сарпи / Вале / сухопутные коридоры Кавказа',
          customsDocs: 'Турецкие экспортные декларации, Carnet TIR',
        },

        // China & Asia Corridors
        {
          id: 'cn-road-direct',
          category: 'china',
          regionBadge: 'Китай • Прямой Автотранспорт',
          from: 'Урумчи, Иу, Гуанчжоу, Шэньчжэнь (Китай)',
          to: 'Казахстан, Армения, Россия, Беларусь',
          time: 'Индивидуально',
          frequency: 'Регулярные прямые автопоезда',
          type: 'Ускоренные еврофуры, тяжеловозы, опасные грузы (ADR)',
          checkpoint: 'Погранпереходы Хоргос / Алашанькоу / Достык',
          customsDocs: 'Китайские экспортные декларации, TIR, CMR',
        },
        {
          id: 'cn-multimodal-sea',
          category: 'china',
          regionBadge: 'Китай • Мультимодал (Море + Авто)',
          from: 'Шанхай, Нинбо, Циндао, Шэньчжэнь (Порты Китая)',
          to: 'Порты Поти / Батуми / Новороссийск ➔ Ереван и СНГ',
          time: 'Индивидуально',
          frequency: 'Еженедельный судоходный сервис (FCL / LCL)',
          type: 'Морские контейнеры 20’GP, 40’HC + вывоз контейнеровозами',
          checkpoint: 'Морские контейнерные терминалы Черного моря',
          customsDocs: 'Коносамент (Bill of Lading), таможенный транзит ВТТ',
        },
        {
          id: 'cn-rail-express',
          category: 'china',
          regionBadge: 'Китай • Ускоренный Ж/Д Контейнер',
          from: 'Сиань, Чэнду, Чжэнчжоу, Ухань (Китай)',
          to: 'ЕАЭС / Армения (с перегрузом на автотранспорт)',
          time: 'Индивидуально',
          frequency: 'Регулярные контейнерные поезда',
          type: 'Контейнерные поезда (Блок-трейны) + доставка авто до двери',
          checkpoint: 'Сухопутные пограничные сухие порты Достык / Алтынколь',
          customsDocs: 'Накладная СМГС (SMGS), электронное декларирование',
        },
      ],
      guaranteeTitle: 'Гарантия бесперебойного прохождения таможенных постов',
      guaranteeDesc: 'Круглосуточный мониторинг очередей на границах, приоритетное экспедирование, проверенные внешнеторговые документы (CMR, Carnet TIR, T1, ЕАЭС) и спутниковый GPS-контроль 24/7.',
      checkStatusBtn: 'Рассчитать стоимость и маршрут',
    },
    requisites: {
      header: 'Юридическая прозрачность',
      title: 'Официальные реквизиты',
      titleAccent: 'компании',
      subtitle: 'Все реквизиты ООО «ЛЕВ ЭНД АВ» для заключения официальных договоров, выставления счетов и безналичных расчетов.',
      legalBadge: 'ЮРИДИЧЕСКОЕ ЛИЦО',
      companyTitle: 'ООО «ЛЕВ ЭНД АВ» (LEV&AV LLC)',
      downloadBtn: 'Скачать реквизиты (.txt)',
      copied: 'Скопировано',
      items: [
        { label: 'Полное наименование', value: 'Общество с ограниченной ответственностью «ЛЕВ ЭНД АВ»', id: 'name_full' },
        { label: 'Краткое наименование', value: 'ООО «ЛЕВ ЭНД АВ» (LEV&AV LLC)', id: 'name_short' },
        { label: 'ИНН компании', value: '02248043', id: 'inn' },
        { label: 'Юридический адрес', value: 'РА, 0046 г. Ереван, ул. С. Таронци 3/1, кв. 18', id: 'address' },
        { label: 'Обслуживающий банк', value: 'ЗАО "ЭВОКАБАНК"', id: 'bank' },
        { label: 'Расчетный счет', value: '16600166153658', id: 'rs' },
        { label: 'Корреспондентский счет', value: '30101810300000000765', id: 'ks' },
        { label: 'БИК банка', value: '044525631', id: 'bik' },
        { label: 'ИНН банка', value: '7718011918', id: 'bank_inn' },
        { label: 'Генеральный директор', value: 'Аветик Зограбян Самвелович', id: 'ceo' },
      ],
      officialNotice: 'Работаем официально по прямым договорам (с НДС и без НДС)',
      residentTag: 'Резидент Республики Армения',
    },
    footer: {
      aboutText: 'ООО «ЛЕВ ЭНД АВ» (LEV&AV LLC) — надежная транспортная компания в сфере международных автомобильных грузоперевозок по СНГ. Собственный автопарк современных тентованных еврофур и рефрижераторов гарантирует сохранность грузов и строгое соблюдение графиков движения.',
      navTitle: 'Навигация',
      contactsTitle: 'Контакты LEV&AV',
      directorLabel: 'Директор (Аветик Самвелович)',
      salesLabel: 'Отдел B2B продаж (Саргис)',
      messengers: '(Telegram, WhatsApp, Viber)',
      backupPhonesLabel: 'Резервные телефоны',
      downloadBtn: 'Скачать карточку компании (.txt)',
      rights: 'Все права защищены.',
      portalType: 'Сайт-визитка транспортной компании',
      location: 'Республика Армения, Ереван',
    },
    modal: {
      badge: 'ОПЕРАТИВНАЯ СВЯЗЬ',
      title: 'Связаться с руководством',
      subtitle: 'Прямой звонок от директора или ведущего B2B-менеджера.',
      nameLabel: 'Ваше имя / Компания',
      namePlaceholder: 'Например, Армен (ООО «Агро-Экспорт»)',
      phoneLabel: 'Контактный телефон',
      phonePlaceholder: '+374 __ ______ или +7 (___) ___-__-__',
      routeLabel: 'Интересующее направление (Необязательно)',
      routePlaceholder: 'Например, Ереван — Москва (рефрижератор)',
      submitBtn: 'Заказать звонок',
      successTitle: 'Запрос принят!',
      successMsg: 'Менеджер ООО «ЛЕВ ЭНД АВ» свяжется с вами в ближайшее время для обсуждения деталей перевозки.',
      closeBtn: 'Закрыть',
    },
    preloader: {
      init: 'Инициализация системы...',
      channels: 'Подключение логистических каналов...',
      fleet: 'Загрузка автопарка и направлений...',
      ui: 'Подготовка интерфейса LEV&AV...',
      ready: 'Готово к работе',
      tagline: 'ЕРЕВАН • СНГ • ЕВРОПА • КИТАЙ • ГЛОБАЛЬНАЯ ЛОГИСТИКА',
    },
  },
  en: {
    nav: {
      about: 'About Us',
      history: 'History',
      fleet: 'Fleet',
      geography: 'Destinations',
      advantages: 'Advantages',
      services: 'Services',
      faq: 'FAQ',
      requisites: 'Requisites',
      contacts: 'Contacts',
      contactBtn: 'Contact Us',
      directPhone: 'Direct Call',
    },
    hero: {
      badge: 'Official International Transport Company Portal',
      title1: 'International Freight Logistics',
      title2: 'Europe • China • CIS Network',
      title3: 'with Dedicated & Partner Fleet',
      description: 'Direct logistics without intermediaries: regular scheduled freight runs across CIS countries (Russia, Belarus, Kazakhstan), direct and multimodal supply chains from China and the European Union. Modern Euro trucks, refrigerated transport, heavy oversized cargo, and complete customs clearance.',
      highlight1Title: 'Own Euro Trucks & Reefers',
      highlight1Sub: 'Continuous climate control',
      highlight2Title: 'Direct Executive Contact',
      highlight2Sub: 'Zero intermediate dispatchers',
      btnHistory: 'Company History',
      btnFleet: 'Our Vehicle Fleet',
      btnContact: 'Get in Touch',
      stats: {
        stat1Num: '14.5k+',
        stat1Label: 'Completed Global Trips',
        stat2Num: '99.8%',
        stat2Label: 'On-time Delivery Rate',
        stat3Num: '100%',
        stat3Label: 'CMR Cargo Insurance',
        stat4Num: '2010',
        stat4Label: 'Operations Since',
      },
      advantages: {
        item1Title: 'Reliability',
        item1Sub: 'We prioritize client trust',
        item2Title: 'Punctuality',
        item2Sub: 'Strict schedule adherence',
        item3Title: 'Coverage',
        item3Sub: 'Across Armenia and beyond',
        item4Title: 'Partnership',
        item4Sub: 'Long-term business relations',
      },
      servicesHeader: 'Our Services',
      servicesTitle: 'Premium Transportation',
      servicesSub: 'Flawless conditions for all logistical demands of your enterprise',
      directions: [
        {
          id: 'road',
          name: 'Road Transportation (Curtainsiders & Reefers)',
          description: 'International transportation of general, LTL, and temperature-controlled cargo across the CIS using our dedicated fleet. Euro trailers and reefers from -20°C to +12°C.',
          speed: 'On Request',
          footnote: '«Own fleet of modern trucks & reefers»',
        },
        {
          id: 'oversized',
          name: 'Oversized & Heavy-Lift Cargo (Forwarding)',
          description: 'Turnkey organization and forwarding of heavy machinery and oversized freight across the CIS. Lowbed trailers, route engineering, and full transit permits.',
          speed: 'On Request',
          footnote: '«Specialized trailers & permits included»',
        },
        {
          id: 'air',
          name: 'Air Freight Delivery',
          description: 'Expedited transport of urgent shipments, commercial packages, and high-value cargo through major international CIS airports.',
          speed: 'On Request',
          footnote: '«Express delivery for urgent cargo»',
        },
        {
          id: 'rail',
          name: 'Railway Freight',
          description: 'Cost-efficient containerized transport (20ft / 40ft) for large volumes of equipment, industrial cargo, and bulk commodities over long distances.',
          speed: 'On Request',
          footnote: '«Intermodal container rail freight»',
        },
        {
          id: 'sea',
          name: 'Maritime Freight',
          description: 'Multimodal container shipping through major sea hubs with seamless road delivery directly to the receiver’s warehouse.',
          speed: 'On Request',
          footnote: '«Multimodal logistics corridors»',
        },
      ],
      faqHeader: 'Answering Your Inquiries',
      faqTitle: 'Frequently Asked Questions',
      faqSub: 'Essential insights on international B2B logistics, customs compliance, and safety guarantees',
      faqItems: [
        {
          question: 'What documentation is required for international freight shipping across the CIS?',
          answer: 'For legal entities, the standard package includes: International Consignment Note (CMR), commercial invoice with detailed item specifications, packing list, technical certificates/passports, and foreign trade contract. Our specialists assist in reviewing and preparing the full dossier for swift customs clearance.'
        },
        {
          question: 'How are freight transit times determined?',
          answer: 'Delivery timeframes are calculated individually for each shipment based on cargo specifications, vehicle type, routing logistics, seasonal weather, and real-time border checkpoint throughput (including the Upper Lars checkpoint). Concrete milestones are stipulated directly in the transport agreement.'
        },
        {
          question: 'Do you ensure precise temperature control and how is cargo integrity guaranteed?',
          answer: 'Yes, our fleet features advanced refrigerated trailers with certified data loggers operating within -20°C to +12°C. Cargo safety is maintained via mandatory chassis sealing, 24/7 real-time GPS telematics, and CMR carrier liability insurance on every voyage.'
        },
        {
          question: 'Do you work with VAT and what are the payment terms for corporate clients?',
          answer: 'Yes, we operate under official B2B contracts with and without VAT. Payments are accepted via wire transfer in RUB, AMD, or other agreed currencies. Flexible terms including credit deferrals are available for long-term partners.'
        }
      ],
      contactsHeader: 'Direct Communication Without Intermediaries',
      contactsTitle: 'Contacts & Executive Team',
      contactsSub: 'Personalized approach for key corporate clients and long-term business partners',
      salesRole: 'B2B SALES',
      salesName: 'Sargis Vardanyan',
      salesDesc: 'Lead Corporate B2B Account Manager',
      salesPhoneLabel: 'Direct Phone Line',
      messengersLabel: 'Instant Messenger Links',
      ceoRole: 'EXECUTIVE MANAGEMENT',
      ceoName: 'Avetik Zohrabyan',
      ceoDesc: 'General Director / CEO, LEV&AV LLC',
      ceoPhoneLabel: 'Director Contact Line',
      ceoEmailLabel: 'Direct Executive E-mail',
      adminRole: 'GENERAL INQUIRIES',
      adminName: 'Administration & Dispatch Desk',
      adminDesc: '24/7 Support / Dispatch and Backup Lines',
      adminPhonesLabel: 'Support Line Numbers',
      adminEmailLabel: 'Corporate E-mail',
      workingHours: 'Hours: Mon-Sat 09:00 - 19:00',
      timezone: 'Yerevan (GMT+4)',
      downloadCardBtn: 'Save Contact (.vcf)',
    },
    history: {
      header: 'Our Milestone & Core Values',
      title: 'Company History of',
      titleAccent: 'LEV&AV',
      subtitle: 'From the initial transport runs to an established international carrier with a dedicated fleet and an unblemished reputation.',
      badge: 'ABOUT LEV&AV LLC',
      mainTitle: 'A Dependable Logistical Bridge between Armenia and CIS Countries',
      desc1: 'LEV&AV LLC has been actively operating in the international freight transportation sector since 2010. Since our very inception, our foremost objective has been delivering honest, direct, and high-standard transportation without intermediary markups.',
      desc2: 'Over the years of steady growth, we built robust technical infrastructure: our own fleet of modern curtainsiders and refrigerated semi-trailers capable of moving general, consolidated, perishable, and oversized goods over any distance.',
      statFounded: 'Operations Since',
      statCoverage: 'CIS Coverage',
      statTransits: 'Secure Deliveries',
      timelineTitle: 'Key Milestones of Development',
      events: [
        {
          year: '2010',
          title: 'Launch of Operations in Yerevan',
          description: 'Inception of logistics operations in Yerevan, assembling a team of expert drivers and establishing the first reliable freight corridors.',
          tag: 'Started in 2010',
        },
        {
          year: '2015',
          title: 'Building Dedicated Fleet of Euro Trucks',
          description: 'Acquisition of modern long-haul tractors and curtainsider trailers to handle general and consolidated cargo across the CIS.',
          tag: 'Dedicated Fleet',
        },
        {
          year: '2019',
          title: 'Launch of Temperature-Controlled Freight',
          description: 'Commissioning modern refrigerated semi-trailers (-20°C to +12°C) with certified thermal loggers for perishable goods.',
          tag: 'Reefer Logistics',
        },
        {
          year: '2024–2026',
          title: 'Belarus & Kazakhstan Expansion, Digital Fleet Tracking',
          description: 'Expanding routes across the CIS. Equipping 100% of vehicles with real-time GPS telematics, CMR cargo insurance, and direct customer access to company leaders.',
          tag: 'Modern Standards',
        },
      ],
      valuesTitle: 'Our Fundamental Principles',
      values: [
        {
          title: 'Direct Access to Leadership',
          description: 'We eliminate intermediary friction. All key logistics decisions are handled directly with the CEO and lead manager.',
        },
        {
          title: 'Proprietary Fleet & Proven Drivers',
          description: 'All tractors and trailers maintain strict technical standards, operated by professional drivers with decade-long international tenure.',
        },
        {
          title: 'Rigorous Commitment & Transparency',
          description: 'Fixed tariffs without hidden surcharges, prompt vehicle dispatch, and proactive tracking updates throughout the route.',
        },
        {
          title: 'Comprehensive Safety & Insurance',
          description: 'Mandatory numbered seals, full shipping documents (CMR, invoices, declarations), and carrier liability insurance coverage.',
        },
      ],
    },
    fleet: {
      header: 'Technical Infrastructure',
      title: 'Proprietary Fleet of',
      titleAccent: 'LEV&AV',
      subtitle: 'Modern European long-haul tractors and reliable trailers ready for demanding routes across all weather conditions.',
      categories: [
        {
          title: 'Refrigerated Semi-Trailers',
          subtitle: 'Temperature control from -20°C to +12°C',
          capacity: 'up to 22 tons / 86–88 m³ / 33 Euro pallets',
          specs: [
            'Certified Thermo King / Carrier autonomous cooling units',
            'Electronic temperature loggers with continuous thermal printouts',
            'Optimal for fresh fruits, vegetables, beverages, cheese, and meats',
            'Rigorous sanitary sanitation and hermetic door seals',
          ],
          highlight: 'Continuous Temperature Monitoring',
        },
        {
          title: 'Curtainsiders & Tilt Trucks (Euro Tents)',
          subtitle: 'General and consolidated cargo across CIS',
          capacity: 'up to 20–22 tons / 90–92 m³ / 33 Euro pallets',
          specs: [
            'All loading options: rear, dual side curtains, and top crane access',
            'Securing straps, wheel chocks, side stakes, and heavy tie-down chains',
            'Heavy-duty reinforced tarpaulins safeguarding from moisture and dust',
            'Mandatory numbered customs seals before departure',
          ],
          highlight: 'Versatile High Capacity',
        },
        {
          title: 'Lowbed Trailers & Heavy Transport',
          subtitle: 'Oversized machinery and industrial equipment',
          capacity: 'Custom payload up to 45+ tons',
          specs: [
            'Low-profile platforms and expandable lowboys with ramps',
            'Transport of construction, mining, and agricultural heavy machinery',
            'Transit permit and route clearance acquisition under one contract',
            'Organization of pilot escort vehicles and safety forwarding',
          ],
          highlight: 'Turnkey Heavy Solutions',
        },
      ],
      capLabel: 'Capacity / Volume:',
      standard: 'Euro-5 / Euro-6 Standards',
      readiness: '100% Trip Ready',
      maintenanceTitle: 'Routine Maintenance',
      maintenanceDesc: 'Every tractor and semi-trailer undergoes comprehensive mechanical inspections before each departure.',
      gpsTitle: '24/7 GPS Telematics',
      gpsDesc: 'Continuous satellite monitoring of transit coordinates, speed, and real-time internal trailer temperatures.',
      crewTitle: 'Seasoned Crew',
      crewDesc: 'Professional international drivers with 10+ years experience navigating mountain passes and winter roads.',
    },
    geography: {
      header: 'International Logistical Corridors',
      title: 'Geographical Reach',
      titleAccent: 'Europe • China • CIS',
      subtitle: 'Well-established direct road and multimodal freight corridors connecting the Republic of Armenia and CIS countries with major industrial and trade centers across Europe, China, and the Eurasian Economic Union.',
      filterAll: 'All Corridors',
      filterCIS: 'CIS & EAEU',
      filterEurope: 'Europe & EU',
      filterChina: 'China & Asia',
      routeNum: 'Corridor #',
      fromLabel: 'Origin:',
      toLabel: 'Destination:',
      frequencyLabel: 'Frequency:',
      truckTypeLabel: 'Transport Type:',
      customsLabel: 'Customs & Hubs:',
      routes: [
        // CIS Corridors
        {
          id: 'cis-moscow',
          category: 'cis',
          regionBadge: 'CIS • Russia',
          from: 'Yerevan (Armenia)',
          to: 'Moscow & Central Federal District (Russia)',
          time: 'On Request',
          frequency: 'Daily scheduled dispatches',
          type: '20t Tilt (90–92 m³), Reefers (-20°C...+12°C)',
          checkpoint: 'Upper Lars Border Point (Georgia — Russia) / Direct Line',
          customsDocs: 'CMR, Commercial Invoice, ST-1, EAEU simplified clearance',
        },
        {
          id: 'cis-spb',
          category: 'cis',
          regionBadge: 'CIS • Russia',
          from: 'Yerevan (Armenia)',
          to: 'Saint Petersburg & North-West (Russia)',
          time: 'On Request',
          frequency: '3–4 runs weekly',
          type: 'Euro curtainsiders, reefers, LTL consolidated shipments',
          checkpoint: 'M-10 / M-11 Federal Highway Transit',
          customsDocs: 'Complete EAEU customs document verification',
        },
        {
          id: 'cis-south',
          category: 'cis',
          regionBadge: 'CIS • Southern Russia',
          from: 'Yerevan (Armenia)',
          to: 'Krasnodar, Rostov-on-Don, Stavropol',
          time: 'On Request',
          frequency: 'Daily (express vehicle supply)',
          type: 'Express perishable food, beverages, and agro produce',
          checkpoint: 'Direct southern transit arterial',
          customsDocs: 'Phytosanitary inspection, continuous thermo-checks, CMR',
        },
        {
          id: 'cis-minsk',
          category: 'cis',
          regionBadge: 'CIS • Belarus',
          from: 'Yerevan (Armenia)',
          to: 'Minsk, Brest, Grodno (Belarus)',
          time: 'On Request',
          frequency: 'Regular scheduled runs',
          type: '20–22t Tilt road trains, consolidated general cargo',
          checkpoint: 'Seamless EAEU customs transit',
          customsDocs: 'Unified Eurasian Customs Union clearance standards',
        },
        {
          id: 'cis-kz',
          category: 'cis',
          regionBadge: 'CIS • Kazakhstan',
          from: 'Yerevan (Armenia)',
          to: 'Almaty, Astana, Shymkent (Kazakhstan)',
          time: 'On Request',
          frequency: '2–3 departures weekly & on demand',
          type: '90–92 m³ Euro trucks, reefers, oversized lowbed trailers',
          checkpoint: 'Trans-Caspian corridor / Northern overland highway',
          customsDocs: 'Electronic EAEU transit declarations & CMR',
        },
        {
          id: 'cis-ural',
          category: 'cis',
          regionBadge: 'CIS • Urals & Siberia',
          from: 'Yerevan (Armenia)',
          to: 'Yekaterinburg, Chelyabinsk, Kazan, Novosibirsk',
          time: 'On Request',
          frequency: 'Regular scheduled line (year-round)',
          type: 'General and groupage freight, industrial raw supplies',
          checkpoint: 'Trans-Siberian Arterial / M-5, M-7 highways',
          customsDocs: 'End-to-end satellite GPS telematics tracking',
        },
        {
          id: 'cis-return',
          category: 'cis',
          regionBadge: 'CIS • Return Freight',
          from: 'Cities across Russia, Belarus & Kazakhstan',
          to: 'Yerevan and Armenia regions',
          time: 'On Request',
          frequency: 'Continuous incoming return traffic',
          type: 'Industrial machinery, metals, building materials, FMCG',
          checkpoint: 'Special preferential rates for return route cargo',
          customsDocs: 'Direct B2B contracts, export/import closing docs',
        },

        // Europe Corridors
        {
          id: 'eu-central',
          category: 'europe',
          regionBadge: 'Europe • Germany / Poland',
          from: 'Germany, Poland, Czechia, Netherlands',
          to: 'Armenia / Russia / Kazakhstan',
          time: 'On Request',
          frequency: 'Weekly consolidated departures',
          type: '92 m³ Tilt Euro trailers, reefers, thermal boxes',
          checkpoint: 'EU Customs Terminals / Carnet TIR / T1 / EX-1 transit',
          customsDocs: 'Export declaration EX-1, transit T1, CMR insurance',
        },
        {
          id: 'eu-south',
          category: 'europe',
          regionBadge: 'Europe • Italy / France',
          from: 'Italy, France, Spain, Austria',
          to: 'Armenia and EAEU states',
          time: 'On Request',
          frequency: 'Regular direct and consolidated freight',
          type: 'General cargo, industrial gear, wine, high-end apparel',
          checkpoint: 'European consolidation hubs (Verona, Milan)',
          customsDocs: 'Full customs clearance, comprehensive CMR coverage',
        },
        {
          id: 'eu-baltic',
          category: 'europe',
          regionBadge: 'Europe • Baltic States',
          from: 'Lithuania (Vilnius, Klaipeda), Latvia (Riga), Estonia',
          to: 'Yerevan and CIS regions',
          time: 'On Request',
          frequency: 'Twice weekly departures',
          type: 'Groupage cargo from 1 pallet, container haulage',
          checkpoint: 'Class-A Consolidation Warehouses in Baltic States',
          customsDocs: 'Repackaging, DataMatrix marking, transit T1 docs',
        },
        {
          id: 'eu-tr',
          category: 'europe',
          regionBadge: 'Turkey • Middle East',
          from: 'Istanbul, Bursa, Izmir, Mersin (Turkey)',
          to: 'Armenia / Georgia / Russia',
          time: 'On Request',
          frequency: 'Regular road freight lines',
          type: 'Textiles, industrial raw materials, auto parts, chemicals',
          checkpoint: 'Sarpi / Vale border posts / Caucasus transit highways',
          customsDocs: 'Turkish export clearance, Carnet TIR forwarding',
        },

        // China & Asia Corridors
        {
          id: 'cn-road-direct',
          category: 'china',
          regionBadge: 'China • Direct Road Freight',
          from: 'Urumqi, Yiwu, Guangzhou, Shenzhen (China)',
          to: 'Kazakhstan, Armenia, Russia, Belarus',
          time: 'On Request',
          frequency: 'Regular direct road trains',
          type: 'Expedited Euro trailers, heavy haulage, ADR chemical cargo',
          checkpoint: 'Khorgos / Alashankou / Dostyk border crossing ports',
          customsDocs: 'Chinese export declarations, TIR, CMR insurance',
        },
        {
          id: 'cn-multimodal-sea',
          category: 'china',
          regionBadge: 'China • Multimodal (Ocean + Road)',
          from: 'Shanghai, Ningbo, Qingdao, Shenzhen (China Ports)',
          to: 'Poti / Batumi / Novorossiysk Ports ➔ Yerevan & CIS',
          time: 'On Request',
          frequency: 'Weekly liner shipping (FCL / LCL)',
          type: '20’GP, 40’HC sea containers + road container chassis haulage',
          checkpoint: 'Black Sea deepwater container terminals',
          customsDocs: 'Bill of Lading (B/L), internal customs transit permits',
        },
        {
          id: 'cn-rail-express',
          category: 'china',
          regionBadge: 'China • Accelerated Rail Express',
          from: "Xi'an, Chengdu, Zhengzhou, Wuhan (China)",
          to: 'EAEU / Armenia (with direct road transfer to destination)',
          time: 'On Request',
          frequency: 'Regular block-train services',
          type: 'Container block-trains + direct door-to-door road delivery',
          checkpoint: 'Overland Dry Ports Dostyk / Altynkol',
          customsDocs: 'SMGS / СМГС rail waybill, electronic declaration',
        },
      ],
      guaranteeTitle: 'Guaranteed Unimpeded Customs Post Transit',
      guaranteeDesc: '24/7 border queue telemetry, priority forwarding credentials, verified international documentation (CMR, Carnet TIR, T1, EAEU), and continuous GPS telematics.',
      checkStatusBtn: 'Calculate Route & Rates',
    },
    requisites: {
      header: 'Corporate Transparency',
      title: 'Official Company',
      titleAccent: 'Requisites',
      subtitle: 'Official corporate credentials of LEV&AV LLC for B2B contract execution, invoicing, and cross-border bank transfers.',
      legalBadge: 'LEGAL ENTITY',
      companyTitle: 'LEV&AV LLC (ООО «ЛЕВ ЭНД АВ»)',
      downloadBtn: 'Download Requisites (.txt)',
      copied: 'Copied',
      items: [
        { label: 'Full Legal Name', value: 'Limited Liability Company «LEV AND AV»', id: 'name_full' },
        { label: 'Short Name', value: 'LEV&AV LLC (ООО «ЛЕВ ЭНД АВ»)', id: 'name_short' },
        { label: 'Tax Identification (TIN/ИНН)', value: '02248043', id: 'inn' },
        { label: 'Registered Address', value: 'RA, 0046 Yerevan, S. Tarontsi St. 3/1, Apt. 18', id: 'address' },
        { label: 'Servicing Bank', value: 'CJSC "EVOCABANK"', id: 'bank' },
        { label: 'Settlement Account', value: '16600166153658', id: 'rs' },
        { label: 'Correspondent Account', value: '30101810300000000765', id: 'ks' },
        { label: 'Bank BIC / SWIFT', value: '044525631', id: 'bik' },
        { label: 'Bank TIN (ИНН Банка)', value: '7718011918', id: 'bank_inn' },
        { label: 'General Director / CEO', value: 'Avetik Zohrabyan', id: 'ceo' },
      ],
      officialNotice: 'Direct B2B contracts available with and without VAT',
      residentTag: 'Resident of Republic of Armenia',
    },
    footer: {
      aboutText: 'LEV&AV LLC is a dependable international freight and logistics company providing direct road, container, and multimodal services across Europe, China, and the CIS network. Our proprietary fleet of modern curtainsiders and refrigerated semi-trailers guarantees cargo safety and strict timeline compliance.',
      navTitle: 'Navigation',
      contactsTitle: 'LEV&AV Contacts',
      directorLabel: 'CEO (Avetik Zohrabyan)',
      salesLabel: 'B2B Sales Desk (Sargis)',
      messengers: '(Telegram, WhatsApp, Viber)',
      backupPhonesLabel: 'Backup Support Lines',
      downloadBtn: 'Download Company Profile (.txt)',
      rights: 'All rights reserved.',
      portalType: 'Official Transport Company Portal',
      location: 'Republic of Armenia, Yerevan',
    },
    modal: {
      badge: 'DIRECT CONTACT',
      title: 'Contact Management',
      subtitle: 'Direct callback from our CEO or Lead B2B Manager.',
      nameLabel: 'Your Name / Company',
      namePlaceholder: 'e.g. David (Agro-Export LLC)',
      phoneLabel: 'Contact Phone Number',
      phonePlaceholder: '+374 __ ______ or international format',
      routeLabel: 'Desired Route (Optional)',
      routePlaceholder: 'e.g. Yerevan — Moscow (Refrigerated)',
      submitBtn: 'Request a Callback',
      successTitle: 'Request Received!',
      successMsg: 'A representative from LEV&AV LLC will reach out to you promptly to coordinate your freight details.',
      closeBtn: 'Close',
    },
    preloader: {
      init: 'Initializing system...',
      channels: 'Connecting logistics channels...',
      fleet: 'Loading vehicle fleet & routes...',
      ui: 'Preparing LEV&AV portal...',
      ready: 'Ready for operations',
      tagline: 'YEREVAN • CIS • EUROPE • CHINA • GLOBAL LOGISTICS',
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>('ru');

  // Load language preference from localStorage on mount if present
  useEffect(() => {
    try {
      const savedLang = localStorage.getItem('levav_lang') as Language;
      if (savedLang === 'ru' || savedLang === 'en') {
        setLangState(savedLang);
      }
    } catch {
      // ignore
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    try {
      localStorage.setItem('levav_lang', newLang);
    } catch {
      // ignore
    }
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
