import { Shipment, FreightRate, CityTerminal } from './types';

export const CITY_TERMINALS: CityTerminal[] = [
  { name: 'Москва', coordinates: { x: 28, y: 52 }, country: 'Россия' },
  { name: 'Санкт-Петербург', coordinates: { x: 22, y: 36 }, country: 'Россия' },
  { name: 'Екатеринбург', coordinates: { x: 44, y: 56 }, country: 'Россия' },
  { name: 'Новосибирск', coordinates: { x: 58, y: 62 }, country: 'Россия' },
  { name: 'Владивосток', coordinates: { x: 92, y: 78 }, country: 'Россия' },
  { name: 'Краснодар', coordinates: { x: 18, y: 68 }, country: 'Россия' },
  { name: 'Калининград', coordinates: { x: 8, y: 38 }, country: 'Россия' },
  { name: 'Минск', coordinates: { x: 14, y: 48 }, country: 'Беларусь' },
  { name: 'Алматы', coordinates: { x: 54, y: 82 }, country: 'Казахстан' },
];

export const FREIGHT_RATES: FreightRate[] = [
  {
    mode: 'road',
    name: 'Автомобильные перевозки',
    pricePerKg: 15,
    pricePerM3: 120,
    basePrice: 1500,
    speedDays: '3-5 дней',
    co2PerKgKm: 0.08,
  },
  {
    mode: 'air',
    name: 'Авиадоставка',
    pricePerKg: 120,
    pricePerM3: 450,
    basePrice: 8000,
    speedDays: '1-2 дня',
    co2PerKgKm: 0.80,
  },
  {
    mode: 'sea',
    name: 'Морские перевозки',
    pricePerKg: 8,
    pricePerM3: 50,
    basePrice: 12000,
    speedDays: '15-25 дней',
    co2PerKgKm: 0.015,
  },
  {
    mode: 'rail',
    name: 'Железнодорожные перевозки',
    pricePerKg: 12,
    pricePerM3: 80,
    basePrice: 3500,
    speedDays: '7-12 дней',
    co2PerKgKm: 0.02,
  },
];

export const CARGO_TYPES = [
  { id: 'general', name: 'Генеральный груз', multiplier: 1.0 },
  { id: 'fragile', name: 'Хрупкий груз (Стекло, Электроника)', multiplier: 1.3 },
  { id: 'temperature', name: 'Температурный (Рефрижератор)', multiplier: 1.4 },
  { id: 'oversized', name: 'Негабаритный / Тяжеловесный', multiplier: 1.5 },
  { id: 'chemical', name: 'Опасный класс (ADR)', multiplier: 1.6 },
];

export const DEFAULT_SHIPMENTS: Shipment[] = [
  {
    id: 'TRK-RU-2041',
    sender: 'ООО "ПромТех"',
    recipient: 'АО "ДальМаш"',
    origin: 'Москва',
    destination: 'Владивосток',
    weight: 450,
    volume: 2.4,
    cargoType: 'Негабаритный / Тяжеловесный',
    mode: 'rail',
    status: 'in_transit',
    currentLocation: 'Иркутск',
    estimatedDelivery: '2026-07-04',
    createdDate: '2026-06-22',
    price: 48500,
    history: [
      {
        id: '1',
        status: 'pending',
        location: 'Москва',
        timestamp: '2026-06-22 10:30',
        description: 'Заявка принята, груз ожидает забора у отправителя.',
      },
      {
        id: '2',
        status: 'sorting',
        location: 'Москва (Склад Юг)',
        timestamp: '2026-06-23 09:15',
        description: 'Груз прибыл на консолидационный склад, отсортирован и подготовлен к отправке.',
      },
      {
        id: '3',
        status: 'in_transit',
        location: 'Москва Терминальная',
        timestamp: '2026-06-24 18:00',
        description: 'Груз погружен в железнодорожный контейнер и отправлен по маршруту Транссиба.',
      },
      {
        id: '4',
        status: 'in_transit',
        location: 'Екатеринбург Hub',
        timestamp: '2026-06-25 14:20',
        description: 'Промежуточное сканирование в распределительном центре Урала. Движение по графику.',
      },
      {
        id: '5',
        status: 'in_transit',
        location: 'Новосибирск Hub',
        timestamp: '2026-06-26 11:40',
        description: 'Груз прошел транзитный пункт в Сибири. Состав следует на восток.',
      },
    ],
  },
  {
    id: 'TRK-AIR-9921',
    sender: 'ИП Воробьев А.П.',
    recipient: 'Магазин "ЭлектроМаркет"',
    origin: 'Екатеринбург',
    destination: 'Москва',
    weight: 25,
    volume: 0.15,
    cargoType: 'Хрупкий груз (Стекло, Электроника)',
    mode: 'air',
    status: 'delivered',
    currentLocation: 'Москва',
    estimatedDelivery: '2026-06-26',
    createdDate: '2026-06-25',
    price: 11200,
    history: [
      {
        id: '1',
        status: 'pending',
        location: 'Екатеринбург',
        timestamp: '2026-06-25 08:00',
        description: 'Заказ оформлен в экспресс-доставку авиа.',
      },
      {
        id: '2',
        status: 'sorting',
        location: 'Екатеринбург Кольцово',
        timestamp: '2026-06-25 11:00',
        description: 'Прошел таможенный и авиационный контроль безопасности на грузовом терминале.',
      },
      {
        id: '3',
        status: 'in_transit',
        location: 'В полете',
        timestamp: '2026-06-25 14:30',
        description: 'Рейс вылетел в аэропорт назначения Шереметьево (Москва).',
      },
      {
        id: '4',
        status: 'sorting',
        location: 'Москва Шереметьево Cargo',
        timestamp: '2026-06-25 18:00',
        description: 'Рейс прибыл. Груз выгружен и принят на терминале сортировки в Москве.',
      },
      {
        id: '5',
        status: 'in_transit',
        location: 'Москва (Склад доставки)',
        timestamp: '2026-06-26 07:30',
        description: 'Передан в курьерскую службу для доставки "до двери".',
      },
      {
        id: '6',
        status: 'delivered',
        location: 'Москва (Адрес получателя)',
        timestamp: '2026-06-26 13:45',
        description: 'Груз успешно доставлен. Получатель подтвердил прием подписью.',
      },
    ],
  },
  {
    id: 'TRK-EU-7731',
    sender: 'Baltic Export Ltd',
    recipient: 'ООО "Анкер"',
    origin: 'Санкт-Петербург',
    destination: 'Калининград',
    weight: 1200,
    volume: 5.8,
    cargoType: 'Генеральный груз',
    mode: 'sea',
    status: 'customs',
    currentLocation: 'Калининград Порт',
    estimatedDelivery: '2026-06-29',
    createdDate: '2026-06-20',
    price: 29800,
    history: [
      {
        id: '1',
        status: 'pending',
        location: 'Санкт-Петербург',
        timestamp: '2026-06-20 14:00',
        description: 'Документы оформлены, контейнер забронирован.',
      },
      {
        id: '2',
        status: 'sorting',
        location: 'Порт Бронка (СПб)',
        timestamp: '2026-06-21 16:30',
        description: 'Контейнер доставлен в порт, пройден портовый весовой контроль.',
      },
      {
        id: '3',
        status: 'in_transit',
        location: 'Финский залив',
        timestamp: '2026-06-23 04:00',
        description: 'Сухогруз вышел из порта Санкт-Петербурга, следует в Балтийск.',
      },
      {
        id: '4',
        status: 'in_transit',
        location: 'Балтийское море',
        timestamp: '2026-06-25 10:00',
        description: 'Судно находится на переходе по Балтийскому морю.',
      },
      {
        id: '5',
        status: 'customs',
        location: 'Порт Балтийск (Калининград)',
        timestamp: '2026-06-27 08:30',
        description: 'Судно пришвартовалось. Контейнер выгружен и передан под таможенный досмотр.',
      },
    ],
  },
];
